// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDbwQ-H_MjqciOW7elKZD_7hzwn7iCd8',
    appId: '1:617402911467:web:79d51d70f8bc0dcfa80cae',
    messagingSenderId: '617402911467',
    projectId: 'achat-645cd',
    authDomain: 'achat-645cd.firebaseapp.com',
    storageBucket: 'achat-645cd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezaoh0LpeKZ-tThv3Hb2sKC610x_JbqQ',
    appId: '1:617402911467:android:bf57b228baf8da83a80cae',
    messagingSenderId: '617402911467',
    projectId: 'achat-645cd',
    storageBucket: 'achat-645cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxiUAgrd5X2md7qnvQImjzLOZcpJ05x84',
    appId: '1:617402911467:ios:38fc096c19ef929ea80cae',
    messagingSenderId: '617402911467',
    projectId: 'achat-645cd',
    storageBucket: 'achat-645cd.firebasestorage.app',
    iosBundleId: 'com.example.aChat',
  );
}
